[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npx serve -s dist"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyMaxRetries = 5

[variables]
VITE_API_URL = "${API_SERVICE_URL}"
